import type { Metadata } from "next";
import "../globals.css";
import { Toaster } from "@/components/ui/sonner";
import { ThemeProvider } from "next-themes";
import { SidebarProvider } from "@/components/ui/sidebar";
import { MessagesSidebarIcons } from "@/components/MessagesSidebarIcons";
import { MessagesSidebar } from "@/components/MessagesSidebar";

export const metadata: Metadata = {
  title: "ThinkSync",
  description: "Generated by create next app",
};

export default function PublicLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <SidebarProvider defaultOpen={false}>
            <div className="flex h-screen">
              {/* Sidebar section */}
              <div>
                <MessagesSidebarIcons />
                <MessagesSidebar />
              </div>
              {/* Main content section */}
              <div className="flex-1">{children}</div>
            </div>
          </SidebarProvider>
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
